services:
  db:
    image: postgres:15.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: moncomptepro
      POSTGRES_PASSWORD: moncomptepro
      POSTGRES_DB: moncomptepro
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  oidc-test-client:
    image: ghcr.io/numerique-gouv/moncomptepro-test-client
    environment:
      PORT: 3001
      # default env var can be found at https://github.com/numerique-gouv/moncomptepro-test-client/blob/master/.env
      HOST: http://localhost:3001
      MCP_CLIENT_ID: client_id
      MCP_PROVIDER: http://localhost:3000/
    network_mode: "host"

  moncomptepro-standard-client:
    image: ghcr.io/numerique-gouv/moncomptepro-test-client
    environment:
      PORT: 4000
      SITE_TITLE: moncomptepro-standard-client
      HOST: http://localhost:4000
      MCP_CLIENT_ID: standard_client_id
      MCP_CLIENT_SECRET: standard_client_secret
      MCP_PROVIDER: http://localhost:3000
      MCP_SCOPES: openid email profile organization
      ACR_VALUE_FOR_2FA: "urn:dinum:ac:classes:consistency-checked-2fa"
      STYLESHEET_URL:
    network_mode: "host"

  moncomptepro-proconnect-federation-client:
    image: ghcr.io/numerique-gouv/moncomptepro-test-client
    environment:
      PORT: 4001
      SITE_TITLE: moncomptepro-proconnect-federation-client
      HOST: http://localhost:4001
      MCP_CLIENT_ID: proconnect_federation_client_id
      MCP_CLIENT_SECRET: proconnect_federation_client_secret
      MCP_PROVIDER: http://localhost:3000
      MCP_SCOPES: openid uid given_name usual_name email siren siret organizational_unit belonging_population phone chorusdt is_service_public is_public_service
      MCP_ID_TOKEN_SIGNED_RESPONSE_ALG: ES256
      MCP_USERINFO_SIGNED_RESPONSE_ALG: ES256
      STYLESHEET_URL:
      LOGIN_HINT: unused1@yopmail.com
    network_mode: "host"

  moncomptepro-legacy-client:
    image: ghcr.io/numerique-gouv/moncomptepro-test-client
    environment:
      PORT: 4002
      SITE_TITLE: moncomptepro-legacy-client
      HOST: http://localhost:4002
      MCP_CLIENT_ID: legacy_client_id
      MCP_CLIENT_SECRET: legacy_client_secret
      MCP_PROVIDER: http://localhost:3000
      MCP_SCOPES: openid email profile phone organizations
      STYLESHEET_URL:
    network_mode: "host"

  moncomptepro-acr-client:
    image: ghcr.io/numerique-gouv/moncomptepro-test-client
    environment:
      PORT: 4003
      SITE_TITLE: moncomptepro-acr-client
      HOST: http://localhost:4003
      MCP_CLIENT_ID: acr_client_id
      MCP_CLIENT_SECRET: acr_client_secret
      MCP_PROVIDER: http://localhost:3000
      MCP_SCOPES: openid email profile organization
      ACR_VALUE_FOR_2FA: urn:dinum:ac:classes:consistency-checked
      STYLESHEET_URL:
    network_mode: "host"

  maildev:
    image: soulteary/maildev
    network_mode: "host"

volumes:
  db-data:
