DELETE FROM users_organizations;
DELETE FROM moderations;
DELETE FROM organizations;
DELETE FROM users_oidc_clients;
DELETE FROM users;
DELETE FROM oidc_clients;
ALTER SEQUENCE moderations_id_seq RESTART WITH 1;
ALTER SEQUENCE organizations_id_seq RESTART WITH 1;
ALTER SEQUENCE users_oidc_clients_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;
ALTER SEQUENCE oidc_clients_id_seq RESTART WITH 1;
