name: 🚢 Release It !

on:
  push:
    branches:
      - master
      - alpha
      - beta
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: 🚢 Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: package.json

      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0

      - run: npm run build:workspaces

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "🔖 Version Packages"
          publish: npx changeset publish
          title: "🔖 Version Packages"
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
